name = "Loading"
uuid = "bb2a6365-84b4-48d3-bb25-aa416b8153f1"
authors = ["Ian Lisien"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
